### PR TITLE
Added Legistar CMS scrapy

### PR DESCRIPTION
**Pull request by andysbolton**
I just added a scrapy that should work for any of the cities that use the Legistar CMS (San Leandro, San Mateo, Cupertino, etc.). The basic idea is that you can pass the scrapy three arguments (`city`, `state`, and `legistar_url`) and it should work as the other scrapies do. A sample command is `scrapy crawl legistar_cms -a legistar_url=https://sanleandro.legistar.com/Calendar.aspx -a city="San Leandro" -a state=CA -o test.json`. It could be modified pretty easily to take a list of arguments (maybe objects with all the city, state, and URL metadata) if we wanted. 

Definitely open to any suggestions for streamlining this scrapy.

### CODE REVIEW

**Comment by chooliu** [comment]
imo let's instead put these under
`/council_crawler/templates/`

**Comment by andysbolton** [comment]
That makes sense, just changed it.

**Comment by chooliu** [comment]
oops, wasn't looking closely -- I'm going to move it again out of "spiders" into `town-council/council_crawler/templates/` in a later commit.

**Comment by chooliu** [comment]
@bstarling @andysbolton

Also, is the `LegistarCms` class compatible with the downstream db stuff? (the queue in which documents are actually pulled)

**Comment by andysbolton** [comment]
@chooliu Yeah, it should be entered into the DB in the same way as the other scrapies.

**Comment by bstarling** [comment]
Sorry i've been slammed but this looks great. Will play around with it as soon as I can. Awesome 👍

**Pull request merged**
